### ISSUE TITLE
Need an AtmosphereInterceptor like API for custom protocol like Socks.js, Socket.IO or atmosphere

### ISSUE THREAD

**Issue by jfarcand** [vibe-project/vibe-java-server#33]
Same functionality of [AtmosphereInterceptor](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereInterceptor.java)

**Comment by flowersinthesand** [comment]
`Action` can be used to achieve such functionalities in conjunction with `Actions`. For example, [`HttpTransportServer`](http://vibe-project.github.io/projects/vibe-java-server/3.0.0-Alpha11/apidocs/org/atmosphere/vibe/transport/http/HttpTransportServer.html) is `Action<ServerHttpExchange>` and [`DefaultServer`](http://vibe-project.github.io/projects/vibe-java-server/3.0.0-Alpha11/apidocs/org/atmosphere/vibe/DefaultServer.html) is `Action<ServerHttpExchange>`.

Likewise, to implement custom protocol, `Action<ServerHttpExchange>` and `Action<ServerWebSocket>` on vibe platform, `Action<ServerTransport>` on vibe transport and `Action<ServerSocket>` on vibe socket can be used. Also `Actions` which is a powerful interface to define a specific event can be used together. https://github.com/vibe-project/vibe-java-platform/issues/43

So I think it's enough to blog its potential use of Action and Actions as AtmosphereInterceptor e.g. implementing custom protocol on vibe platform, vibe transport and vibe socket.
